### PR TITLE
Fixes #8: Fix for wrong argument supplied at _get_database fn call

### LINKED ISSUE #8: Support for multiple DB connections
From what I can see in the codebase, the `pgtrigger.core` module uses `from django.db import connection` to deliver the required DB connection, which means that it uses the `default` connection from `django.db.connections` and there is no way to change / override / configure that behaviour.

In my specific case, I need to support different groups of models which use different DBs and the default connection is not being used at all, which means that with a hardcoded default DB connection, I am unable to use this package on any of my projects.

In an ideal situation, I would like to be able to do the following:

```
from django.db import connections
import pgtrigger

@pgtrigger.register(
    pgtrigger.Trigger(
        level=pgtrigger.Statement,
        when=pgtrigger.After,
        operation=pgtrigger.Delete,
        referencing=pgtrigger.Referencing(old='old_values', new='new_values'),
        func=_some_trigger_function,
        db_connection=connections["some_connection"]
    )
)
class SomeModel(models.Model):
    pass
```

or 

```
from django.db import connections
import pgtrigger

@pgtrigger.register(
    db_connection=connections["some_connection"]
    pgtrigger.Trigger(
        level=pgtrigger.Statement,
        when=pgtrigger.After,
        operation=pgtrigger.Delete,
        referencing=pgtrigger.Referencing(old='old_values', new='new_values'),
        func=_some_trigger_function
    )
)
class SomeModel(models.Model):
    pass
```

which would allow me to specify the required connection via `db_connection` parameter.

Are there any plans to support multiple DB connections on a per trigger definition basis?

### PR DESCRIPTION
**Pull request by arpitremarkable**

### CODE REVIEW

**Comment by tomage** [comment]
Ah, good catch!
Any chance you can replicate the bug in a unit-test? On one hand, that'd be more proper, but on the other, this is fairly obvious fix, and trivial.

Odd that the test suite wouldn't have caught it, but that does happen from time to time.

Sidenote: I'm also looking into why our documentation didn't get built and pushed out. I may wanna fix that before we merge this in, so that we get proper docs for when this hits master. I'll get back to this in an hour or two.

**Comment by wesleykendall** [comment]
@arpitremarkable @tomage lgtm! The tests likely didn't catch it because it was valid code that was unasserted. I'm not too concerned about testing logging output and this seems like an obvious fix. 

Thanks for the contribution!

**Comment by tomage** [comment]
@arpitremarkable Yep! I think we can merge more or less as-is!

There's one thing I'd like to suggest if you don't mind, which would be to add a relevant git trailer so that the version gets bumped (see more here: https://github.com/jyveapp/django-pgtrigger/blob/master/CONTRIBUTING.rst#releases-and-versioning).

We generally use git-tidy to achieve this - but this can really be trivially done by just slightly modifying your commit message.

It currently reads:

```
Fix for wrong argument supplied at _get_database fn call
```

But if you could change it to, say:
```
Fix for wrong argument supplied at _get_database fn call

Type: bug
```

(There must be one empty line between the message itself, and the first trailer apparently: https://git-scm.com/docs/git-interpret-trailers#_description).

then it'll make our build pipeline bump the version number properly.

You can easily achieve this with the following (just in case you haven't come across this before :) ):
```
$ git checkout fix-multi-db  # just to be on your branch for sure
$ git commit --amend  # should open up editor to let you edit the commit message
$ git push -f  # prob. need to force-push the new commit out
```

Thanks again for the contribution!

**Comment by tomage** [comment]
Heads-up - I also just pushed out a minor patch to fix the documentation building - so you could also rebase this branch with latest/greatest in the master branch.

Also, if you like, I could totally cherry-pick your commit - amend the commit message and get it merged in ASAP if you like (it would keep you as the commit author - for attribution, tho I'll be attached to it as the committer).

Totally up to you @arpitremarkable  :)

**Comment by arpitremarkable** [comment]
I've updated the commit.
Can not run make setup though so not able to make docs or test
Let me know if it is good to go

**Review by tomage — APPROVED** [review]
Looks good to me! Sorry for being so late to this. Not sure why the tests didn't run, but I see no reason for this not working.

Approving, but might see if @wesleykendall  is up for merging in, as he also has another patch to bring in.

**Pull request merged**
